# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskID', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created', models.DateTimeField()),
                ('startDate', models.DateField()),
                ('dueDate', models.DateField()),
            ],
        ),
    ]
