# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dueDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='startDate',
            field=models.DateField(blank=True),
        ),
    ]
