# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplanner', '0004_auto_20170819_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-priority', '-due_date', 'created_date']},
        ),
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Top')], default=2),
        ),
    ]
