# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplanner', '0005_auto_20170819_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
