# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplanner', '0006_auto_20170819_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='estimated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='time_estimated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Top')], default=1),
        ),
    ]
